### ISSUE TITLE
Issues with instructions running accelerate.bat first time

### ISSUE THREAD

**Issue by Markdood88** [olegchomp/TDDepthAnything#1]
Just something to note when running accelerate.bat for the first time on python 3.11.8:

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycuda
Failed to build pycuda
ERROR: Could not build wheels for pycuda, which is required to install pyproject.toml-based projects
Found existing installation: nvidia-cudnn-cu11 8.9.4.25
Uninstalling nvidia-cudnn-cu11-8.9.4.25:
  Successfully uninstalled nvidia-cudnn-cu11-8.9.4.25
  
  
Also getting an issue after including the models in checkpoints about :

Preparing for model acceleration...
Traceback (most recent call last):
  File "D:\Experimental\TDDepthAnything-main\TDDepthAnything-main\accelerate_model.py", line 5, in <module>
    from polygraphy.backend.trt import (
ModuleNotFoundError: No module named 'polygraphy'
Press any key to continue . . .

**Comment by olegchomp** [comment]
Solved in discord. 
Added [Microsoft Visual C++](https://visualstudio.microsoft.com/visual-cpp-build-tools/) to readme
