### ISSUE TITLE
TopArray license not included in code

### ISSUE THREAD

**Issue by keithlostracco** [olegchomp/TDDepthAnything#5]
Hi I noticed that the license specified in TopArray was not included the code. Would you be able include it in the extension where the TopArray classes are used? Or if you loaded TopArray.py into the network and imported the module into your extension the license would be include without it being in your extension. 

Ah I didn't realize you linked the the library on the readme. Thanks!

**Comment by olegchomp** [comment]
Added
Thank you!
https://github.com/olegchomp/TDDepthAnything/blob/3f18a573644cc4313e8318ab4db1eaf31520b692/DepthAnythingExt.py#L1-L25
