### ISSUE TITLE
This plugin so amazing, but is there a way to fix the flickering problem when use the webcam stream？

### ISSUE THREAD

**Issue by N0e0N** [olegchomp/TDDepthAnything#6]

**Comment by olegchomp** [comment]
It's limitation of original repo. You can try to smooth it with feedback loop in TouchDesigner

**Comment by N0e0N** [comment]
What determines this parameter, is it that bigger is better?
![image](https://github.com/olegchomp/TDDepthAnything/assets/78398751/b3d9d30e-4300-40b8-a437-cabbb85fe990)
![1714313448855](https://github.com/olegchomp/TDDepthAnything/assets/78398751/ad7743fc-1c0c-46b8-8d72-93ff44562b6c)

**Comment by N0e0N** [comment]
> It's limitation of original repo. You can try to smooth it with feedback loop in TouchDesigner↳

oh，it is a good idea！
