### ISSUE TITLE
Can't import torch

### ISSUE THREAD

**Issue by NairoDorian** [olegchomp/TDDepthAnything#8]
Added 'C:\TDDepthAnything\venv\Lib\site-packages' to sys.path.
DAT compile error: /project1/TDDepthAnything/DepthAnythingExt
Traceback (most recent call last):
  File "/project1/TDDepthAnything/DepthAnythingExt", line 28
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TDDepthAnything\venv\Lib\site-packages\torch\__init__.py", line 141
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\TDDepthAnything\venv\Lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

It seems there is an issue when importing pytorch

Has anyone solved that

**Comment by NairoDorian** [comment]
I've found https://github.com/pytorch/pytorch/issues/125109

Modifying the accelerate script to install the 2.2.x version of pytorch instead of 2.3.0 that was released last week fixed this issue for me

**Comment by olegchomp** [comment]
Thank you! Fixed with https://github.com/olegchomp/TDDepthAnything/commit/e5dfe397041de3b275b64a4cbf743f116023d408
